site_name: nanoNAS Documentation
site_url: https://nanonas.readthedocs.io
site_description: Professional Neural Architecture Search Platform - Research-Grade AutoML Framework
site_author: AutoML Research Team

repo_url: https://github.com/Ratz-innovator/AutoMl-CodeGen
repo_name: Ratz-innovator/AutoMl-CodeGen
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2024 AutoML Research Team

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - announce.dismiss
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Inter
    code: JetBrains Mono
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.ico
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

extra:
  version:
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Ratz-innovator/AutoMl-CodeGen
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/nanonas/
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/nanonas/nanonas
  analytics:
    provider: google
    property: G-XXXXXXXXXX
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

extra_css:
  - assets/css/custom.css
  - assets/css/termynal.css

extra_javascript:
  - assets/js/termynal.js
  - assets/js/custom.js

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - git-committers:
      repository: Ratz-innovator/AutoMl-CodeGen
      branch: main
  - mkdocs-jupyter:
      execute: false
      kernel_name: python3
      include_source: true
  - gallery:
      examples_dirs: ../examples/tutorials
      gallery_dirs: gallery
  - mkdocstrings:
      handlers:
        python:
          paths: [../]
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_signature_annotations: true
            show_source: false
            show_bases: true
            show_root_heading: true
            show_root_toc_entry: true
            show_object_full_path: false
            show_category_heading: true
            group_by_category: true
            heading_level: 2

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: Ratz-innovator
      repo: AutoMl-CodeGen
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home:
    - index.md
    - installation.md
    - quickstart.md
    - changelog.md
  - User Guide:
    - user-guide/index.md
    - user-guide/basic-usage.md
    - user-guide/configuration.md
    - user-guide/search-strategies.md
    - user-guide/search-spaces.md
    - user-guide/datasets.md
    - user-guide/visualization.md
    - user-guide/benchmarking.md
    - user-guide/deployment.md
  - Tutorials:
    - tutorials/index.md
    - tutorials/getting-started.md
    - tutorials/evolutionary-nas.md
    - tutorials/darts-tutorial.md
    - tutorials/pc-darts-tutorial.md
    - tutorials/ensemble-search.md
    - tutorials/multi-objective.md
    - tutorials/custom-search-space.md
    - tutorials/advanced-visualization.md
    - tutorials/production-deployment.md
  - Gallery:
    - gallery/index.md
  - API Reference:
    - api/index.md
    - api/core.md
    - api/search.md
    - api/models.md
    - api/benchmarks.md
    - api/visualization.md
    - api/utils.md
    - api/server.md
  - Research:
    - research/index.md
    - research/algorithms.md
    - research/theoretical-foundation.md
    - research/experimental-results.md
    - research/comparison-studies.md
    - research/ablation-studies.md
    - research/publications.md
  - Development:
    - development/index.md
    - development/contributing.md
    - development/architecture.md
    - development/testing.md
    - development/release-process.md
    - development/roadmap.md
  - Blog:
    - blog/index.md 